steps:
  # Configure docker authentication
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'auth'
      - 'configure-docker'
      - 'us-central1-docker.pkg.dev'

  # Debug step to show environment
  - name: 'ubuntu'
    args: 
      - bash
      - -c
      - |
        echo "Current directory contents:"
        ls -la
        echo "Project ID: $PROJECT_ID"
        echo "Build ID: $BUILD_ID"
    
  # Build the container
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/backup-scripts/backup-script:latest'
      - '--no-cache'
      - '.'
  
  # Push to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/backup-scripts/backup-script:latest'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/backup-scripts/backup-script:latest'

options:
  logging: CLOUD_LOGGING_ONLY